var n1 : number = 1;
var n2 : number = 2;

console.log("Addition");
console.log(n1 + n2);
console.log("Subtraction");
console.log(n1 - n2);
console.log("Multiplication");
console.log(n1 * n2);
console.log("Division");
console.log(n1 / n2);
console.log("Modulus");
console.log(n1 % n2);
console.log("Increment");
console.log(n1++);
console.log("Decrement");
console.log(n1--);
console.log("Increment");
console.log(++n1);
console.log("Decrement");
console.log(--n1);
